export const engToKor: Record<string, string> = {
  email: '이메일',
  nickname: '닉네임',
  gender: '성별',
  achievement: '업적',
  userInfo: '회원정보',
  avatar: '아바타',
  chatting: '채팅',
  home: '홈',
  speech: '말하기',
  name: '이름',
  birthday: '생일',
  personality: '성격',
  job: '직업',
  residence: '거주지',
  mypage: '내정보',
  nickEdit: '닉네임 변경',
  pwdEdit: '비밀번호 변경',
  infoEdit: '정보 관리',
  qnaEdit: '질문 관리',
};
